version: "3.9"

services:
  app:
    build: .
    volumes:
      - ./data:/app/data
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: dw_burnout
      POSTGRES_USER: grupo6
      POSTGRES_PASSWORD: burnout123
    ports:
      - "5432:5432"